# Compatible with vscode rest-client extension
@base_url=http://localhost:3333

###

# @name create_products

POST {{base_url}}/products
Content-Type: application/json

{
  "name": "Pencil",
  "price": 1.2,
  "quantity": 100
}
